name:                twain
version:             1.0.0.0
github:              "alexmingoia/twain"
license:             BSD3
author:              "Alex Mingoia"
maintainer:          "alex@alexmingoia.com"
copyright:           "2021 Alexander C. Mingoia"
category:            Web
synopsis:            Tiny web application framework for WAI.

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
# description:         Please see the README on GitHub at <https://github.com/alexmingoia/twain#readme>

dependencies:
- aeson >= 1.4 && < 1.7
- base >= 4.7 && < 5
- bytestring >= 0.10 && < 0.11
- case-insensitive >= 1.2 && < 1.3
- cookie >= 0.4 && < 0.6
- either >= 5.0 && < 5.1
- http-types >= 0.12 && < 0.13
- text >= 1.2.3 && < 1.3
- time >= 1.8 && < 1.9.9
- transformers >= 0.5.6 && < 0.6
- wai >= 3.2 && < 3.3
- wai-extra >= 3.0 && < 3.2
- warp >= 3.2 && < 3.4

library:
  exposed-modules:
    Web.Twain
    Web.Twain.Types
  other-modules:
    Web.Twain.Internal
  source-dirs: src
  default-extensions:
  - OverloadedStrings
